### ISSUE TITLE
Place Keyword Punchlist

### ISSUE THREAD

**Issue by torrin47** [USEPA/EPA_Non-geo_Metadata_Editor#86]
Checkboxes aren't shown in IE11

Can we allow users to enter custom place keywords? If it can be done in less than 2 hours, let's do it, otherwise, we'll push back.

**Comment by aergul** [comment]
Now using a different widget that is IE-friendly.

The new widget can be configured to allow entry of custom place keywords but that alone would result in custom place keywords migrating to general keywords when the record is re-opened because that's where a keyword goes when it's not in one of the static lists associated with Place/ISO/EPA keywords. We could create a new tag in the record to store our housekeeping info and then use that when the record is loaded to put the custom place keywords back under place keywords. That would work in the mechanical sense, however I'd worry that it could be confusing to anyone who looks at the raw record. Thoughts?

**Comment by jzichichi** [comment]
@aergul  - I'm not too sure in terms of the users of this tool who looks at the raw metadata, so it's hard to say if the approach of a custom tag would have a lot of confused users or if there would possibly just be a couple who would notice.  Also, is there an issue if these records are contributed to data.gov? I would look to @torrin47 for input there..... 

I tested the new drop-down in IE; I don't see checkboxes still but perhaps that isn't part of the new widget's capabilities?  I wasn't sure given your comment above.

**Comment by aergul** [comment]
@jzichichi I should have mentioned that the new widget does not use checkboxes to select multiple entries, I apologize. Thanks for your comments as I realized we could further simplify entry by not closing the drop down upon selection and removing selected entries. Updated as said.

**Comment by jzichichi** [comment]
@aergul - OK great. I like the recent update much better now that it doesn't close every time I make a selection.  Passing to @torrin47 for review.

**Comment by torrin47** [comment]
Thanks for the work last week, I'm back in the office. I like the new widget - it's smooth and intuitive.  And I totally get how custom place keywords would be problematic when importing records to the tool. I think the best option for now (until we get the go ahead to create an optional enhancement to select bounding box extent or wire up the dropdown to geonames.org) is to add guidance to users letting them know to use the general keywords section for place names not in our list. Validation still requires them to choose at least one place keyword on our list, which is a bit of a bind - do we suggest they simply choose "United States"? Or add "other" as an option?  My inclination is the former. Thoughts?

**Comment by aergul** [comment]
I'd agree with the former. I think anything in there should actually describe a place.
